<a href="https://colab.research.google.com/github/Danielle504/CAP4630/blob/master/HW_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Homework 4

Number 1

Using only numpy, implement the function conv2d. It takes as input input_mat and kernel_mat and outputs output_mat. All variables are square matrices. It should compute the convolution of input_mat with the kernel kernel_mat using valid padding.

Note that the size s of the kernel matrix can also be an even number.

In [0]:
import numpy as np
from scipy import signal

In [0]:
def conv2d(input_mat, kernel_mat):

  if(np.shape(input_mat) < np.shape(kernel_mat)):
    print("ERROR: Kernel > Input")
    return []

  kernel_mat = np.flip(kernel_mat)

  w = np.shape(input_mat)[0] - np.shape(kernel_mat)[0] + 1
  l = np.shape(input_mat)[1] - np.shape(kernel_mat)[1] + 1

  output_mat = np.zeros((w, l))

  kernel_width = np.shape(kernel_mat)[0]
  kernel_length = np.shape(kernel_mat)[1]

  for i in range(w):
    for j in range(l):
      for k in range(kernel_width):
        for m in range(kernel_length):
          output_mat[i][j] = output_mat[i][j] + (input_mat[k+i][m+j] * kernel_mat[k][m])

  return output_mat

In [7]:
input_mat = []
kernel_mat = []
expected_mat = []

# Test1
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 1, 2, 1],
                      [1, 2, 1, 2],
                      [2, 1, 2, 1]]))

kernel_mat.append(np.array([[1, 0],
                       [0, 1]]))

expected_mat.append(np.array([[2, 4, 2],
                                [4, 2, 4],
                                [2, 4, 2]]))

# Test2
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

kernel_mat.append(np.array([[1, 0],
                            [0, 1]]))

expected_mat.append(np.array([[2, 0, 0], [0, 2, 0], [0, 0, 2]]))

# Test3
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, -1],
                       [-1, 0]]))

expected_mat.append(np.array([[ 1, -1,  0], [-1,  1, -1],[ 0, -1,  1]]))

# Test4
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append(np.array([[4]]))


# Test5
input_mat.append(np.array([[1, -1],
                       [-1, 0]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append([])


for i in range(len(input_mat)):
  # uncomment line for student code testing
  output_mat = conv2d(input_mat[i], kernel_mat[i])

  # # uncomment lines below (and comment line above) for generating test cases.
  # if input_mat[i].shape[0] < kernel_mat[i].shape[0]:
  #   output_mat = []
  # else:
  #   output_mat = signal.convolve2d(input_mat[i], kernel_mat[i], mode='valid')

  print(output_mat)

  if np.array_equal(output_mat, expected_mat[i]):
    print("YASSS YOU GO\n")
  else:
    print("BOOO GO BACK\n")

[[10. 22. 34. 46.]
 [60. 72. 84. 96.]
 [10. 22. 34. 46.]
 [60. 72. 84. 96.]]
BOOO GO BACK

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
YASSS YOU GO

[[ 1. -1.  0.]
 [-1.  1. -1.]
 [ 0. -1.  1.]]
YASSS YOU GO

[[4.]]
YASSS YOU GO

ERROR: Kernel > Input
[]
YASSS YOU GO

