<a href="https://colab.research.google.com/github/Danielle504/CAP4630/blob/master/HW_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Homework 4

Number 1

Using only numpy, implement the function conv2d. It takes as input input_mat and kernel_mat and outputs output_mat. All variables are square matrices. It should compute the convolution of input_mat with the kernel kernel_mat using valid padding.

Note that the size s of the kernel matrix can also be an even number.

In [0]:
import numpy as np
from scipy import signal

In [0]:
def conv2d(input_mat, kernel_mat):

  if(np.shape(input_mat) < np.shape(kernel_mat)):
    print("ERROR: Kernel > Input")
    return []

  kernel_mat = np.flip(kernel_mat)

  w = np.shape(input_mat)[0] - np.shape(kernel_mat)[0] + 1
  l = np.shape(input_mat)[1] - np.shape(kernel_mat)[1] + 1

  output_mat = np.zeros((w, l))

  kernel_width = np.shape(kernel_mat)[0]
  kernel_length = np.shape(kernel_mat)[1]

  for i in range(w):
    for j in range(l):
      for k in range(kernel_width):
        for m in range(kernel_length):
          output_mat[i][j] = output_mat[i][j] + (input_mat[k+i][m+j] * kernel_mat[k][m])

  return output_mat

In [0]:
input_mat = []
kernel_mat = []
expected_mat = []

# Test1
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 1, 2, 1],
                      [1, 2, 1, 2],
                      [2, 1, 2, 1]]))

kernel_mat.append(np.array([[1, 0],
                       [0, 1]]))

expected_mat.append(np.array([[2, 4, 2],
                                [4, 2, 4],
                                [2, 4, 2]]))

# Test2
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

kernel_mat.append(np.array([[1, 0],
                            [0, 1]]))

expected_mat.append(np.array([[2, 0, 0], 
                              [0, 2, 0], 
                              [0, 0, 2]]))

# Test3
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, -1],
                       [-1, 0]]))

expected_mat.append(np.array([[ 1, -1,  0], 
                              [-1,  1, -1],
                              [ 0, -1,  1]]))

# Test4
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append(np.array([[4]]))


# Test5
input_mat.append(np.array([[1, -1],
                       [-1, 0]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append([])


for i in range(len(input_mat)):
  # uncomment line for student code testing
  output_mat = conv2d(input_mat[i], kernel_mat[i])

  # # uncomment lines below (and comment line above) for generating test cases.
  # if input_mat[i].shape[0] < kernel_mat[i].shape[0]:
  #   output_mat = []
  # else:
  #   output_mat = signal.convolve2d(input_mat[i], kernel_mat[i], mode='valid')

  print(output_mat)

  if np.array_equal(output_mat, expected_mat[i]):
    print("YASSS YOU GO\n")
  else:
    print("BOOO GO BACK\n")

[[2. 4. 2.]
 [4. 2. 4.]
 [2. 4. 2.]]
YASSS YOU GO

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
YASSS YOU GO

[[ 1. -1.  0.]
 [-1.  1. -1.]
 [ 0. -1.  1.]]
YASSS YOU GO

[[4.]]
YASSS YOU GO

ERROR: Kernel > Input
[]
YASSS YOU GO



Problem 2

Using only numpy, implement the function maxpooling2d. It takes as input input_mat and s and outputs output_mat. The variables input_mat and output_mat are square matrices and s is an integer. It should compute the maxpooling operation on input_mat using window of shape s times s.

In [0]:
import numpy as np
import skimage.measure

In [0]:
def maxpooling2d(input_mat, s):
  
  if(np.shape(input_mat) < (s,s)):
    print("ERROR: Filter > Input")
    return []

  w = np.shape(input_mat)[0]
  l = np.shape(input_mat)[1]

  a = int(w/s)
  output_mat = np.zeros((a,a))

  for i in range(0,w,s):
    for j in range(0,l,s):
        
      for k in range(s):
        for m in range(s):
          
          try :
            output_mat[int(i/s)][int(j/s)] = max(output_mat[int(i/s)][int(j/s)], (input_mat[k+int(i)][m+int(j)]))
          except:
            pass
          
  return output_mat

In [0]:
input_mat = []
expected_mat = []
s = []
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 4, 2, 1],
                      [1, 2, 4, 2],
                      [2, 1, 2, 1]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                                [2, 4]]))

input_mat.append(np.array([[1, 2, 1, 2, 4, 5],
                      [2, 4, 2, 1, 0, 3],
                      [1, 2, 4, 2, 4, 5],
                      [2, 1, 2, 1, 2, 1],
                      [1, 1, 2, 3, 1, 2],
                      [1, 1, 2, 3, 1, 2]]))
s.append(2)

expected_mat.append([[4, 2, 5],
 [2, 4, 5],
 [1, 3, 2]])


#Extra row and column test case
input_mat.append(np.array([[1, 2, 1, 2, 4],
                      [2, 4, 2, 1 , 4],
                      [1, 2, 4, 2, 4],
                      [2, 1, 2, 1, 4],
                      [2, 1, 2, 1, 4]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                                [2, 4]]))




for i in range(len(input_mat)):
  # uncomment top line and comment second line to test code
  output_mat = maxpooling2d(input_mat[i], s[i])
  # output_mat = skimage.measure.block_reduce(input_mat[i], (s[i],s[i]), np.max)

  print(output_mat)

  if np.array_equal(output_mat, expected_mat[i]):
    print("YASSS YOU GO\n")
  else:
    print("BOOO GO BACK\n")

[[4. 2.]
 [2. 4.]]
YASSS YOU GO

[[4. 2. 5.]
 [2. 4. 5.]
 [1. 3. 2.]]
YASSS YOU GO

[[4. 2.]
 [2. 4.]]
YASSS YOU GO



HW 3:
 
https://colab.research.google.com/drive/11YtPfRzbd66ZW96YCeNTmm4OI0kvsOmv

https://colab.research.google.com/drive/1lwGtlD7qn2Sq2ceveUINO_W7zO6yBQeC